#!/bin/bash

#
# Start script for ivil
#
#
BASE=`dirname "$0"`
# TODO make it independent from my path. How?
BYTECODE=$HOME/eclipse/pseudo.bytecode

SYS_DIR=$BASE/sys:$BYTECODE/sys

#
# Logging
OPTIONS=
if [ -r $BASE/logging.properties ]
then
  OPTIONS="-Djava.util.logging.config.file=$BASE/logging.properties $OPTIONS"
fi

#
# verbose
if [ "$1" = "-v" ]
then
  shift
  OPTIONS="-Dpseudo.log=20"
fi

#
# debugging w/o suspend
if [ "$1" = "-D" ]
then
  shift 
  OPTIONS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1234 $OPTIONS"
fi

#
# debugging w/ suspend
if [ "$1" = "-Ds" ]
then
  shift 
  OPTIONS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1234 $OPTIONS"
fi

#
# Profiling (not together with -D)
if [ "$1" = "-J" ]
then
  shift
  OPTIONS="-Xrunhprof:cpu=samples,depth=10,thread=y $OPTIONS"
fi

#
# additional VM parameter (-Dpseudo.showtype=true for instance)
while [ "${1:0:2}" = "-X" ]
do
  OPTIONS="${1:2} $OPTIONS"
  shift 
done

java -ea $OPTIONS \
  -Dpseudo.baseDir=$BASE \
  -Dpseudo.sysDir=$SYS_DIR \
  -Xmx300M \
  -jar $BASE/ivil.jar "$@"
