#!/bin/bash

#
# Start script for command line ivil
#
# The environment variable IVIL_SYSPATH points to directories which contain
# built-in ivil files
CANONICAL=`readlink -f "$0"`
BASE=`dirname "$CANONICAL"`

SYS_DIR=$BASE/sys:$IVIL_SYSPATH

#
# Java executable
if [ -z $JAVA_CMD ]
then
  JAVA_CMD=java
fi

#
# Logging
OPTIONS=
if [ -r $BASE/logging.properties ]
then
  OPTIONS="-Djava.util.logging.config.file=$BASE/logging.properties $OPTIONS"
fi


#
# Debug command line options
#

verbose=false

while [ "${1:0:2}" == "-D" ]
do
  case ${1:0:3}
  in

    #
    # debug help
    -Dh)
       shift
       echo "-Dh    this help"
       echo "-Dv    verbose output (log level=10)"
       echo "-Ds    debugging with suspend (waiting for debugger)"
       echo "-Dc    debugging w/o suspend (continuing)"
       echo "-Dj    enable profiling"
       echo "-DX<Y> pass option <Y> through to the virtual machine"
       exit 0
       ;;
   
    #
    # verbose
    -Dv)
       shift
       verbose=true
       OPTIONS="-Dpseudo.log=10 -Dpseudo.showtypes=true $OPTIONS"
       ;;
       
    #
    # debugging w/ suspend
    -Ds)
       OPTIONS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1234 $OPTIONS"
       shift 
       ;;

    #
    # debugging  w/o suspend  ( c(ontinue) )
    -Dc)
       OPTIONS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1234 $OPTIONS"
       shift 
       ;;
       
    #
    # Profiling
    -Dj)
       shift
       OPTIONS="-Xrunhprof:cpu=samples,depth=10,thread=y $OPTIONS"
       ;;

    #
    # additional VM parameter (-Dpseudo.showtype=true for instance)
    -DX)
       OPTIONS="${1:3} $OPTIONS"
       shift 
       ;;
       
    # error message otherwise
    *)
       echo "unknown debug option: $1"
       shift
       ;;
  esac
done

$verbose && echo "Options: $OPTIONS"
$verbose && $JAVA_CMD -version

$JAVA_CMD -ea $OPTIONS \
  -Dpseudo.baseDir=$BASE \
  -Dpseudo.sysDir=$SYS_DIR \
  -Xmx300M \
  -cp $BASE/ivil.jar de.uka.iti.pseudo.cmd.Main "$@"
