#!/bin/sh

#
# Start script for Pseudo / Bookey
#
# TODO make it independent from my paths. How?
#

BASE=$HOME/eclipse/pseudo
BYTECODE=$HOME/eclipse/pseudo.bytecode

SYS_DIR=$BASE/sys:$BYTECODE/sys

if [ -r $BASE/logging.properties ]
then
  LOG_OPT="-Djava.util.logging.config.file=$BASE/logging.properties"
fi

java -ea $LOG_OPT \
  -Dpseudo.baseDir=$BASE \
  -Dpseudo.sysDir=$SYS_DIR \
  -jar $BASE/pseudo.jar "$@"
