#
# This file was generated by PSEUDO
# which is copyright (C) 2009 Universitaet Karlsruhe, Germany
#    written by Mattias Ulbrich
#

include "$bytecode.p"

(* Class Declarations *)
function
  reftype C_A unique

(* Class Hierarchy *)
