package de.uka.iti.pseudo.parser.boogie.ast.expression;

import java.util.ArrayList;
import java.util.List;

import de.uka.iti.pseudo.parser.boogie.ASTVisitException;
import de.uka.iti.pseudo.parser.boogie.ASTVisitor;
import de.uka.iti.pseudo.parser.boogie.Token;

public final class EqualsExpression extends Expression {

    private final List<Expression> operands;
    /**
     * true iff the expression was generated by != and needs a surrounding not
     */
    private final boolean inequality;

    public EqualsExpression(Token loc, Expression rval, Expression tmp, boolean inequality) {
        super(loc);

        this.inequality = inequality;

        operands = new ArrayList<Expression>(2);
        operands.add(rval);
        operands.add(tmp);

        addChildren(operands);
    }

    @Override
    public List<Expression> getOperands() {
        return operands;
    }

    public boolean isInequality() {
        return inequality;
    }

    @Override
    public void visit(ASTVisitor v) throws ASTVisitException {
        v.visit(this);
    }

}
