/* Generated By:JavaCC: Do not edit this line. ASTParserConstants.java */
/*
 * Copyright (C) 2008 J�lio Vilmar Gesser.
 * Copyright (C) 2011 Timm Felden.
 *
 * This file is part of Java 1.5/JML* parser and Abstract Syntax Tree.
 *
 * Java 1.5 parser and Abstract Syntax Tree is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Java 1.5 parser and Abstract Syntax Tree is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Java 1.5 parser and Abstract Syntax Tree.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.uka.iti.ivil.jml.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN_SPEC = 6;
  /** RegularExpression Id. */
  int BEGIN_SINGLE_SPEC = 7;
  /** RegularExpression Id. */
  int END_SPEC = 9;
  /** RegularExpression Id. */
  int END_SINGLE_SPEC = 10;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int JAVA_DOC_COMMENT = 14;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 15;
  /** RegularExpression Id. */
  int ABSTRACT = 17;
  /** RegularExpression Id. */
  int ASSERT = 18;
  /** RegularExpression Id. */
  int BOOLEAN = 19;
  /** RegularExpression Id. */
  int BREAK = 20;
  /** RegularExpression Id. */
  int BYTE = 21;
  /** RegularExpression Id. */
  int CASE = 22;
  /** RegularExpression Id. */
  int CATCH = 23;
  /** RegularExpression Id. */
  int CHAR = 24;
  /** RegularExpression Id. */
  int CLASS = 25;
  /** RegularExpression Id. */
  int CONST = 26;
  /** RegularExpression Id. */
  int CONTINUE = 27;
  /** RegularExpression Id. */
  int _DEFAULT = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int ENUM = 32;
  /** RegularExpression Id. */
  int EXTENDS = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int FINAL = 35;
  /** RegularExpression Id. */
  int FINALLY = 36;
  /** RegularExpression Id. */
  int FLOAT = 37;
  /** RegularExpression Id. */
  int FOR = 38;
  /** RegularExpression Id. */
  int GOTO = 39;
  /** RegularExpression Id. */
  int IF = 40;
  /** RegularExpression Id. */
  int IMPLEMENTS = 41;
  /** RegularExpression Id. */
  int IMPORT = 42;
  /** RegularExpression Id. */
  int INSTANCEOF = 43;
  /** RegularExpression Id. */
  int INT = 44;
  /** RegularExpression Id. */
  int INTERFACE = 45;
  /** RegularExpression Id. */
  int LONG = 46;
  /** RegularExpression Id. */
  int NATIVE = 47;
  /** RegularExpression Id. */
  int NEW = 48;
  /** RegularExpression Id. */
  int NULL = 49;
  /** RegularExpression Id. */
  int PACKAGE = 50;
  /** RegularExpression Id. */
  int PRIVATE = 51;
  /** RegularExpression Id. */
  int PROTECTED = 52;
  /** RegularExpression Id. */
  int PUBLIC = 53;
  /** RegularExpression Id. */
  int RETURN = 54;
  /** RegularExpression Id. */
  int SHORT = 55;
  /** RegularExpression Id. */
  int STATIC = 56;
  /** RegularExpression Id. */
  int STRICTFP = 57;
  /** RegularExpression Id. */
  int SUPER = 58;
  /** RegularExpression Id. */
  int SWITCH = 59;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 60;
  /** RegularExpression Id. */
  int THIS = 61;
  /** RegularExpression Id. */
  int THROW = 62;
  /** RegularExpression Id. */
  int THROWS = 63;
  /** RegularExpression Id. */
  int TRANSIENT = 64;
  /** RegularExpression Id. */
  int TRUE = 65;
  /** RegularExpression Id. */
  int TRY = 66;
  /** RegularExpression Id. */
  int VOID = 67;
  /** RegularExpression Id. */
  int VOLATILE = 68;
  /** RegularExpression Id. */
  int WHILE = 69;
  /** RegularExpression Id. */
  int ALSO = 70;
  /** RegularExpression Id. */
  int ASSIGNABLE = 71;
  /** RegularExpression Id. */
  int ASSUME = 72;
  /** RegularExpression Id. */
  int AXIOM = 73;
  /** RegularExpression Id. */
  int QUANTIFIER = 74;
  /** RegularExpression Id. */
  int DIVERGES = 75;
  /** RegularExpression Id. */
  int DECREASING = 76;
  /** RegularExpression Id. */
  int ENSURES = 77;
  /** RegularExpression Id. */
  int EVERYTHING = 78;
  /** RegularExpression Id. */
  int GHOST = 79;
  /** RegularExpression Id. */
  int INV = 80;
  /** RegularExpression Id. */
  int INVARIANT = 81;
  /** RegularExpression Id. */
  int JML_MODIFIER = 82;
  /** RegularExpression Id. */
  int LOOP_INVARIANT = 83;
  /** RegularExpression Id. */
  int MEASURED_BY = 84;
  /** RegularExpression Id. */
  int MODEL = 85;
  /** RegularExpression Id. */
  int NOTHING = 86;
  /** RegularExpression Id. */
  int REQUIRES = 87;
  /** RegularExpression Id. */
  int REPRESENTS = 88;
  /** RegularExpression Id. */
  int SIGNALS = 89;
  /** RegularExpression Id. */
  int SUCH_THAT = 90;
  /** RegularExpression Id. */
  int TYPE = 91;
  /** RegularExpression Id. */
  int TYPEOF = 92;
  /** RegularExpression Id. */
  int ELEMENTTYPE = 93;
  /** RegularExpression Id. */
  int SUBTYPE = 94;
  /** RegularExpression Id. */
  int JML_IDENTIFIER = 95;
  /** RegularExpression Id. */
  int JMLLETTER = 96;
  /** RegularExpression Id. */
  int JMLPART_LETTER = 97;
  /** RegularExpression Id. */
  int LONG_LITERAL = 98;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 99;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 100;
  /** RegularExpression Id. */
  int HEX_LITERAL = 101;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 102;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 103;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 104;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 105;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 106;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 107;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 108;
  /** RegularExpression Id. */
  int STRING_LITERAL = 109;
  /** RegularExpression Id. */
  int IDENTIFIER = 110;
  /** RegularExpression Id. */
  int LETTER = 111;
  /** RegularExpression Id. */
  int PART_LETTER = 112;
  /** RegularExpression Id. */
  int LPAREN = 113;
  /** RegularExpression Id. */
  int RPAREN = 114;
  /** RegularExpression Id. */
  int LBRACE = 115;
  /** RegularExpression Id. */
  int RBRACE = 116;
  /** RegularExpression Id. */
  int LBRACKET = 117;
  /** RegularExpression Id. */
  int RBRACKET = 118;
  /** RegularExpression Id. */
  int SEMICOLON = 119;
  /** RegularExpression Id. */
  int COMMA = 120;
  /** RegularExpression Id. */
  int DOT = 121;
  /** RegularExpression Id. */
  int AT = 122;
  /** RegularExpression Id. */
  int ASSIGN = 123;
  /** RegularExpression Id. */
  int LT = 124;
  /** RegularExpression Id. */
  int BANG = 125;
  /** RegularExpression Id. */
  int TILDE = 126;
  /** RegularExpression Id. */
  int HOOK = 127;
  /** RegularExpression Id. */
  int COLON = 128;
  /** RegularExpression Id. */
  int EQ = 129;
  /** RegularExpression Id. */
  int LE = 130;
  /** RegularExpression Id. */
  int GE = 131;
  /** RegularExpression Id. */
  int NE = 132;
  /** RegularExpression Id. */
  int SC_OR = 133;
  /** RegularExpression Id. */
  int SC_AND = 134;
  /** RegularExpression Id. */
  int INCR = 135;
  /** RegularExpression Id. */
  int DECR = 136;
  /** RegularExpression Id. */
  int PLUS = 137;
  /** RegularExpression Id. */
  int MINUS = 138;
  /** RegularExpression Id. */
  int STAR = 139;
  /** RegularExpression Id. */
  int SLASH = 140;
  /** RegularExpression Id. */
  int BIT_AND = 141;
  /** RegularExpression Id. */
  int BIT_OR = 142;
  /** RegularExpression Id. */
  int XOR = 143;
  /** RegularExpression Id. */
  int REM = 144;
  /** RegularExpression Id. */
  int LSHIFT = 145;
  /** RegularExpression Id. */
  int PLUSASSIGN = 146;
  /** RegularExpression Id. */
  int MINUSASSIGN = 147;
  /** RegularExpression Id. */
  int STARASSIGN = 148;
  /** RegularExpression Id. */
  int SLASHASSIGN = 149;
  /** RegularExpression Id. */
  int ANDASSIGN = 150;
  /** RegularExpression Id. */
  int ORASSIGN = 151;
  /** RegularExpression Id. */
  int XORASSIGN = 152;
  /** RegularExpression Id. */
  int REMASSIGN = 153;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 154;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 155;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 156;
  /** RegularExpression Id. */
  int ELLIPSIS = 157;
  /** RegularExpression Id. */
  int EQUIVALENCE = 158;
  /** RegularExpression Id. */
  int INEQUIVALENCE = 159;
  /** RegularExpression Id. */
  int IMPLIES = 160;
  /** RegularExpression Id. */
  int EXPLIES = 161;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 162;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 163;
  /** RegularExpression Id. */
  int GT = 164;
  /** RegularExpression Id. */
  int UNKNOWN_CHARACTER_SEQUENCE = 165;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SPEC = 1;
  /** Lexical state. */
  int SSPEC = 2;
  /** Lexical state. */
  int IN_JAVA_DOC_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"/*@\"",
    "\"//@\"",
    "\"@\"",
    "\"*/\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 12>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 16>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"also\"",
    "\"assignable\"",
    "\"assume\"",
    "\"axiom\"",
    "<QUANTIFIER>",
    "\"diverges\"",
    "\"decreasing\"",
    "\"ensures\"",
    "\"\\\\everything\"",
    "\"ghost\"",
    "\"\\\\inv\"",
    "<INVARIANT>",
    "<JML_MODIFIER>",
    "\"loop_invariant\"",
    "\"measured_by\"",
    "\"model\"",
    "\"\\\\nothing\"",
    "\"requires\"",
    "\"represents\"",
    "\"signals\"",
    "\"\\\\such_that\"",
    "\"\\\\type\"",
    "\"\\\\typeof\"",
    "\"\\\\elemtype\"",
    "\"<:\"",
    "<JML_IDENTIFIER>",
    "<JMLLETTER>",
    "<JMLPART_LETTER>",
    "<LONG_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"<==>\"",
    "\"<=!=>\"",
    "\"==>\"",
    "\"<==\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "<UNKNOWN_CHARACTER_SEQUENCE>",
    "\"\\u001a\"",
    "\"..\"",
  };

}
